create statistic
Kaminari26/java-explore-with-me pull request #5
Opened 2023-07-24 13:18 UTC by Kaminari26

2023-07-25 14:45 UTC, YazykovMikhail requested changes

2023-07-25 14:45 UTC, YazykovMikhail commented on statistics/stat-client/src/main/java/ru/practicum/client/BaseClient.java
> +public class BaseClient {
Тут нужен еще сервис, который будет запрашивать данные из stat-service вызывая его эндпоинты по http.

2023-07-25 14:45 UTC, YazykovMikhail commented on statistics/stat-client/src/main/java/ru/practicum/model/Hit.java
> +package ru.practicum.model;
эта папка не нужна, у тебя есть целый модуль stat-dto используй модели от туда, в этом его и смсылс, что бы ипользовать в другиз модуля и не делать одинаковые дто возде

2023-07-25 14:45 UTC, YazykovMikhail commented on statistics/stat-service/src/main/java/ru/practicum/controller/StatServiceController.java
> +    public List<HitDto> getHit(Timestamp start, Timestamp end, String uris, Boolean unique) {
```
	public ResponseEntity<List<ViewStats>> getStats(@RequestParam @NonNull String start,
													@RequestParam @NonNull String end,
													@RequestParam(required = false) List<String> uris,
													@RequestParam(required = false) Integer limit,
													@RequestParam(defaultValue = "false") boolean unique) {
```
//@RequestParam(required = false) Integer limit	- может быть	тематикой доп задания, в соотвествеии с 
4.Определится с тематикой дополнительной функциональности, которую вы будете реализовывать

2023-07-25 14:45 UTC, YazykovMikhail commented on statistics/stat-service/src/main/java/ru/practicum/controller/StatServiceController.java
> +        System.out.println(uris);
думаю это лишнее)
должно быть логивроание

2023-07-25 14:45 UTC, YazykovMikhail commented on statistics/stat-service/src/main/java/ru/practicum/controller/StatServiceController.java
> +        System.out.println(list);
думаю это лишнее)
должно быть логивроание

2023-07-25 14:45 UTC, YazykovMikhail commented on statistics/stat-service/src/main/java/ru/practicum/model/Hit.java
> +public class Hit {
Используй модели из stats-dto модуля

2023-07-25 14:45 UTC, YazykovMikhail commented on statistics/stat-service/src/main/java/ru/practicum/controller/StatServiceController.java
> +    }
стоит добавить логирвоанеи что все успешно добавлено, иначе будет непонтяно когда завершился процесс добавления

2023-07-25 14:45 UTC, YazykovMikhail commented on statistics/stat-service/src/main/java/ru/practicum/controller/StatServiceController.java
> +        List<HitDto> list = statService.getHit(start, end, uris, unique);
лист плохре название переменной, никогда не называй переменыые по стурктуре данных

2023-07-25 15:59 UTC, Kaminari26 commented on statistics/stat-service/src/main/java/ru/practicum/controller/StatServiceController.java
> +    public List<HitDto> getHit(Timestamp start, Timestamp end, String uris, Boolean unique) {
я хотел другую)

2023-07-26 14:18 UTC, YazykovMikhail commented on statistics/stat-service/src/main/java/ru/practicum/controller/StatServiceController.java
> +    public List<HitDto> getHit(Timestamp start, Timestamp end, String uris, Boolean unique) {
Пусть будет другая, ок
но остальные поля должны быт ьв таком виде, в соотвествии со схемой

2023-07-26 14:23 UTC, YazykovMikhail requested changes

2023-07-26 14:23 UTC, YazykovMikhail commented on statistics/stat-dto/src/main/java/ru/practicum/model/Hit.java
> +public class Hit {
Моделе тут не место, у тебя модуль называется stat-dto.
Отвечает за dto, модели в каждом модули свои

2023-07-26 14:23 UTC, YazykovMikhail commented on statistics/stat-service/src/main/java/ru/practicum/controller/StatServiceController.java
> +    public void createItem(@RequestBody Hit hit) {
На вход должны приходить dto, модели используется только в репозитории.

2023-07-26 19:26 UTC, Kaminari26 commented on statistics/stat-service/src/main/java/ru/practicum/controller/StatServiceController.java
> +    public List<HitDto> getHit(Timestamp start, Timestamp end, String uris, Boolean unique) {
ну у меня че то не работало, я заметил что могу парсить стринг)

2023-07-27 12:30 UTC, merged